-- AlterTable
ALTER TABLE "Report" ALTER COLUMN "shipping" SET DEFAULT 0.0,
ALTER COLUMN "shipping" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "vitality" SET DEFAULT 0.0,
ALTER COLUMN "vitality" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "stability" SET DEFAULT 0.0,
ALTER COLUMN "stability" SET DATA TYPE DECIMAL(65,30);
